import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import { getSession } from "../lib/auth";
import Providers from "../lib/authProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import LoadingInterceptor from "./loading.client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <AntdRegistry>
            <NavBar />
            <LoadingInterceptor />
            {children}
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
