import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import { getSession } from "../lib/auth";
import Providers from "../lib/authProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import LoadingInterceptor from "./loading.client";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: ".public/assets/fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session}>
          <AntdRegistry>
            <NavBar />
            <LoadingInterceptor />
            {children}
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
